# Generated by Django 3.2.4 on 2021-06-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('first_name', models.CharField(help_text='Name author', max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(help_text='Name author', max_length=150, verbose_name='last name')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('name', models.TextField(help_text='category name', max_length=255, verbose_name='category name')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified at')),
                ('title', models.CharField(help_text='Book title', max_length=255, verbose_name='book title')),
                ('sub_title', models.CharField(help_text='Book sub title', max_length=255, verbose_name='book sub title')),
                ('publish_date', models.DateTimeField()),
                ('editor', models.CharField(blank=True, help_text='Book editor', max_length=150, null=True, verbose_name='book editor')),
                ('description', models.TextField(help_text='Book description', verbose_name='book description')),
                ('image', models.TextField(blank=True, help_text='Book image', null=True, verbose_name='book image')),
                ('source_book', models.CharField(blank=True, help_text='Book source', max_length=30, null=True, verbose_name='book source')),
                ('authors', models.ManyToManyField(to='api.Author')),
                ('categories', models.ManyToManyField(to='api.Category')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
